import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  // Rutas para usuario 'Administrador'
  // { path: '/inicio', title: 'Inicio', icon: 'home', class: '', badge: '', badgeClass: '',
  // isExternalLink: false, submenu: [], userType: '2', tooltip: '' },
  {
    path: '/slides',
    title: 'Slides',
    icon: 'view_carousel',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/cursos',
    title: 'Cursos',
    icon: 'book',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/solicitudes',
    title: 'Solicitudes',
    icon: 'description',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/productos',
    title: 'Productos',
    icon: 'local_offer',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/socios',
    title: 'Listado de socios',
    icon: 'people',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/noticias',
    title: 'Noticias',
    icon: 'list_alt',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '',
    title: 'Comunicación',
    icon: 'message',
    class: 'has-sub',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [
      {
        path: '/mensajes/mensajes-presidente',
        title: 'Mensajes del presidente',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        userType: '2',
        tooltip: '',
      },
      {
        path: '/mensajes/notificaciones',
        title: 'Notificaciones',
        icon: '',
        class: '',
        badge: '',
        badgeClass: '',
        isExternalLink: false,
        submenu: [],
        userType: '2',
        tooltip: '',
      },
    ],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/pagos',
    title: 'Pagos',
    icon: 'point_of_sale',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/agenda',
    title: 'Agenda',
    icon: 'date_range',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/normateca',
    title: 'Normateca',
    icon: 'library_books',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/bandeja-cotizaciones',
    title: 'Cotizaciones',
    icon: 'calculate',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
  {
    path: '/convenios',
    title: 'Convenios',
    icon: 'supervised_user_circle',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    userType: '2',
    tooltip: '',
  },
];
